[package]
name = "libminetestworld"
version = "0.1.0"
authors = ["Joz <joz@spline.de>"]

[dependencies]
rusqlite = "0.19.0"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
zstd = "0.10"
